name: Codacy Security Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Remove old codacy report
        run: |
          git rm --ignore-unmatch reports/codacy-issues.sarif
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: reports/codacy-issues.sarif
          format: sarif
          directory: ${GITHUB_WORKSPACE}/web_scraper_all.py
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will handover control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: reports/codacy-issues.sarif
      
      - name: Git Pull
        run: git pull
      - run: |
          if [ $(git update-index --refresh && git diff-index --quiet HEAD --) = ""]; then
            echo "IS_FILE_CHANGED=true" >> $GITHUB_ENV
          else
            echo "IS_FILE_CHANGED=false" >> $GITHUB_ENV
          fi
      - if: ${{ env.IS_FILE_CHANGED }}
        name: Commit & Push Artifacts to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: ${{ github.workflow }}, ${{ github.job }}-${{ github.run_number }} Commit & Push Artifacts

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: reports/codacy-issues.sarif