name: Snyk Test for Python
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Remove old snyk report
        run: |
          git rm --ignore-unmatch reports/snyk-issues.sarif
          git rm --ignore-unmatch reports/snyk.json
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install flake8 pytest cyclonedx-bom pyinstaller pdoc bandit pylint coverage
          pip install -r requirements.txt
          pip freeze > requirements-frozen.txt
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --file=requirements-frozen.txt --package-manager=pip --skip-unresolved --sarif-file-output=reports/snyk-issues.sarif --json-file-output=reports/snyk-issues.json
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: reports/snyk-issues.sarif

      - name: remove req-frozen.txt
        run: git rm --ignore-unmatch requirements-frozen.txt && rm -f requirements-frozen.txt
      - name: Git Pull
        run: git pull
      - run: |
          if git diff-index --quiet HEAD --; then
            echo "IS_FILE_CHANGED=true" >> $GITHUB_ENV
          else
            echo "IS_FILE_CHANGED=false" >> $GITHUB_ENV
          fi
      - if: ${{ env.IS_FILE_CHANGED == true}}
        name: Commit & Push Artifacts to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: ${{ github.workflow }}, ${{ github.job }}-${{ github.run_number }} Commit & Push Artifacts

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: reports/snyk-issues.sarif reports/snyk-issues.json