name: Snyk Test for Python
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Remove old snyk report
        run: |
          git rm --ignore-unmatch ${{ github.workspace }}/reports/snyk-issues.sarif
          git rm --ignore-unmatch ${{ github.workspace }}/reports/snyk.json
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=./reports/snyk-issues.sarif --json-file-output=./reports/snyk-issues.json --exclude=test,reports,dist,docs,md,yml,js,index,html
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./reports/snyk-issues.sarif

      - name: Git Pull
        run: git pull
      - name: Commit & Push Artifacts to Repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: ${{ github.workflow }}${{ github.job }}-${{ github.run_number }} Commit & Push Artifacts

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: ./reports/snyk-issues.sarif ./reports/snyk-issues.json