name: tes

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    -name: Echo
      run: |
        echo ${ github.workflow }${ github.job }-${ github.run.number }
        echo ${{ github.workflow }}${{ github.job }}-${{ github.run.number }}
